const authTypes = {
  SIGN_USER_UP_START: 'SIGN_USER_UP_START',
  SIGN_USER_UP_SUCCESS: 'SIGN_USER_UP_SUCCESS',
  SIGN_USER_UP_FAILURE: 'SIGN_USER_UP_FAILURE',
  LOG_USER_IN_START: 'LOG_USER_IN_START',
  LOG_USER_IN_SUCCESS: 'LOG_USER_IN_SUCCESS',
  LOG_USER_IN_FAILURE: 'LOG_USER_IN_FAILURE',
  LOG_USER_OUT_START: 'LOG_USER_OUT_START',
  LOG_USER_OUT_SUCCESS: 'LOG_USER_OUT_SUCCESS',
  LOG_USER_OUT_FAILURE: 'LOG_USER_OUT_FAILURE',
  EDIT_USER_START: 'EDIT_USER_START',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',
  REMOVE_USER_START: 'REMOVE_USER_START',
  REMOVE_USER_SUCCESS: 'REMOVE_USER_SUCCESS',
  REMOVE_USER_FAILURE: 'REMOVE_USER_FAILURE',
};

export default authTypes;
